<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-8D76I4T" failures="1" tests="4" name="homepage" time="22.866" errors="0" timestamp="2020-08-24T19:57:52 EDT">
  <testcase classname="tests.homepagetest" name="homepageTests" time="2.625">
    <failure type="java.lang.AssertionError" message="expected [30] but found [40]">
      <![CDATA[java.lang.AssertionError: expected [30] but found [40]
at tests.homepagetest.homepageTests(homepagetest.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- homepageTests -->
  <testcase classname="tests.login" name="login" time="5.65"/>
  <testcase classname="tests.login" name="logins" time="0.007"/>
  <testcase classname="tests.login" name="logins" time="0.007"/>
  <testcase classname="core.BaseTest" name="@AfterSuite tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase classname="core.BaseTest" name="@BeforeSuite reportSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite reportSetup -->
</testsuite> <!-- homepage -->
